projects:
  splitit:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        dev: ${env:PRISMA_ENDPOINT}
        # prod:
        #   url: ${env:PROD_PRISMA_ENDPOINT}
        #   headers:
        #     Authorization: "Bearer ${env:AUTH_TOKEN_ENV}"
